
<MonInterface>
    entre: idEntre
    message: idMessage
    GridLayout:
        size: root.width, root.height
        cols: 1
        GridLayout:
            cols: 2        
            Label: 
                text: "Bonjour"
            TextInput:
                id:idEntre
        Button:
            text:"Valider"
            on_press:root.clicBouton()
        Label:
            id: idMessage
            text:""